INSERT INTO OPERATION_TYPES VALUES('1', 'Compra à Vista');
INSERT INTO OPERATION_TYPES VALUES('2', 'Compra Parcelada');
INSERT INTO OPERATION_TYPES VALUES('3', 'Saque');
INSERT INTO OPERATION_TYPES VALUES('4', 'Pagamento');

COMMIT;