CREATE TABLE ACCOUNTS
(
	ACCOUNT_ID	    NUMBER(20) NOT NULL,
	DOCUMENT_NUMBER     NUMBER(14) NOT NULL
)
;
ALTER TABLE ACCOUNTS ADD CONSTRAINT PK_ACCOUNTS PRIMARY KEY (ACCOUNT_ID)
;

CREATE SEQUENCE ACCOUNTS_SEQ
;

CREATE TABLE OPERATION_TYPES
(
	OPERATION_TYPE_I    CHAR(1) NOT NULL,
	DESCRIPTION         VARCHAR2(20)
)
;
ALTER TABLE OPERATION_TYPES ADD CONSTRAINT PK_OPERATION_TYPES PRIMARY KEY (OPERATION_TYPE_ID)
;

CREATE TABLE TRANSACTIONS
(
	TRANSACTION_ID		NUMBER(20) NOT NULL,
	ACCOUNT_ID		NUMBER(20) NOT NULL,
	OPERATION_TYPE_ID	CHAR(1) NOT NULL,
	AMOUNT			NUMBER,
	EVENT_DATE 		DATE
)
;
ALTER TABLE TRANSACTIONS ADD CONSTRAINT PK_TRANSACTIONS PRIMARY KEY (TRANSACTION_ID)
;
CREATE SEQUENCE TRANSACTIONS_SEQ
;

ALTER TABLE TRANSACTIONS ADD CONSTRAINT FK_TRANSACTIONS_ACCOUNTS 
	FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNTS (ACCOUNT_ID)
;

ALTER TABLE TRANSACTIONS ADD CONSTRAINT FK_TRANSACTIONS_OPERATION_TYPES
	FOREIGN KEY (OPERATION_TYPE_ID) REFERENCES OPERATION_TYPES (OPERATION_TYPE_ID)
;

COMMIT;